<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>ManagementProducts.Use.Cases</AssemblyName>
		<RootNamespace>ManagementProducts.Use.Cases</RootNamespace>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Master\Master.csproj" />
	</ItemGroup>

</Project>
