<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>ManagementProducts.SharedDto</AssemblyName>
		<RootNamespace>ManagementProducts.SharedDto</RootNamespace>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
